listen: ':123'
metric: ':9090'
geodb: GeoLite2-Country.mmdb
worker: 1
rate: 4

server:
    - time1.aliyun.com
    - time2.aliyun.com
    - time3.aliyun.com
    - time4.aliyun.com
    - time5.aliyun.com
    - time6.aliyun.com
    - time7.aliyun.com
